server:
  port: 80
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7002/eureka,http://rb.com:7001/eureka #集群版本
      #defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: order80
    prefer-ip-address: true
spring:
  application:
    name: cloud-cinsumer-order
