server:
  port: 7001
eureka:
  instance:
    hostname: rb.com #Eureka服务端的实例名称
  client:
    register-with-eureka: false #表示不将自己注册到Eureka中
    fetch-registry: false #表示自己就是服务中心，不需要抓取其他信息
    service-url:
      defaultZone: http://localhost:7002/eureka/
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/